### ISSUE TITLE
これってなんのためにつくってるんだっけ？

### ISSUE THREAD

**Issue by Takeuchi-yuya** [Takeuchi-yuya/Ksimulation#16]
なんか俺が作ったら？って言った気がするけどいまいちなんでつくったのか分からなくなってきた
https://github.com/Takeuchi-yuya/Ksimulation/blob/master/project/subtool.py#L70

**Comment by tou-fuu** [comment]
L70は単純にルンゲの計算に必要な変数を計算してるんだけど、、
あれ、L70のコードについてってことであってるよね？

**Comment by Takeuchi-yuya** [comment]
すまん、行数おかしくなってた
下のコード必要ないかもって思ってるって話
今後利用できるかなこれ？東條の意見求む
```
    np.save('runge_posi',x)

```

**Comment by tou-fuu** [comment]
現段階ではいらないと思う。
でも、dtをどんどん小さくしていって、ルンゲの計算が重くなったらその結果を保存しておくと楽になると思う。
